// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9dO4JMN53x_kkXblCXa28eYCqiL-ySWk',
    appId: '1:798101406714:web:0aa8f5707b58e01572da43',
    messagingSenderId: '798101406714',
    projectId: 'retry-e095a',
    authDomain: 'retry-e095a.firebaseapp.com',
    storageBucket: 'retry-e095a.appspot.com',
    measurementId: 'G-QM5T1SQ5N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXjgMTnpxAVeqyyZMeRIi7lg9q4lwHauw',
    appId: '1:798101406714:android:5d32d7cb5edd382a72da43',
    messagingSenderId: '798101406714',
    projectId: 'retry-e095a',
    storageBucket: 'retry-e095a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbVTncya3I47jfGJBjvEkT4fGDgostAdk',
    appId: '1:798101406714:ios:d6f3d68cc1b8a1f672da43',
    messagingSenderId: '798101406714',
    projectId: 'retry-e095a',
    storageBucket: 'retry-e095a.appspot.com',
    iosBundleId: 'com.example.retryloginlogout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbVTncya3I47jfGJBjvEkT4fGDgostAdk',
    appId: '1:798101406714:ios:d6f3d68cc1b8a1f672da43',
    messagingSenderId: '798101406714',
    projectId: 'retry-e095a',
    storageBucket: 'retry-e095a.appspot.com',
    iosBundleId: 'com.example.retryloginlogout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9dO4JMN53x_kkXblCXa28eYCqiL-ySWk',
    appId: '1:798101406714:web:1e4bdda8ac26890372da43',
    messagingSenderId: '798101406714',
    projectId: 'retry-e095a',
    authDomain: 'retry-e095a.firebaseapp.com',
    storageBucket: 'retry-e095a.appspot.com',
    measurementId: 'G-CZKGBJN3SH',
  );
}
